version: '3.8'

services:
  web:
    image: jitsi/web:stable
    ports:
      - '8000:80'
      - '8443:443'
    environment:
      - ENABLE_AUTH=1
      - JWT_ENABLED=1
      - JWT_SECRET=YOUR_SECRET
      - JWT_APP_ID=YOUR_APP_ID
      - JWT_ISSUER=YOUR_JWT_ISSUER
      - XMPP_SERVER=prosody
      - XMPP_BOSH_URL_BASE=http://prosody:5280
    networks:
      - jitsi-net

  prosody:
    image: jitsi/prosody:stable
    ports:
      - '5222:5222'
      - '5280:5280'
    environment:
      - AUTH_TYPE=internal
      - ENABLE_AUTH=1
      - JICOFO_AUTH_PASSWORD=YOUR_JICOFO_AUTH_PASSWORD
      - JVB_AUTH_PASSWORD=YOUR_JVB_AUTH_PASSWORD
    networks:
      - jitsi-net

  jicofo:
    image: jitsi/jicofo:stable
    environment:
      - XMPP_DOMAIN=meet.jitsi
      - XMPP_AUTH_DOMAIN=auth.meet.jitsi
      - XMPP_INTERNAL_MUC_DOMAIN=internal.auth.meet.jitsi
      - XMPP_SERVER=prosody
      - JICOFO_AUTH_PASSWORD=YOUR_JICOFO_AUTH_PASSWORD
    networks:
      - jitsi-net

  jvb:
    image: jitsi/jvb:stable
    ports:
      - '10000:10000/udp'
    environment:
      - XMPP_SERVER=prosody
      - JVB_AUTH_USER=jvb
      - JVB_INTERNAL_MUC_DOMAIN=internal.auth.meet.jitsi
      - JVB_AUTH_PASSWORD=YOUR_JVB_AUTH_PASSWORD
    networks:
      - jitsi-net

  java-app:
    build: .
    volumes:
      - D:\Programing\Bachelor's work\3D-video-conferencing-system:/app
    command: java -jar /app/your-java-app.jar
    environment:
      - JVB_HOST=jvb
      - JVB_PORT=10000
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
    depends_on:
      - jvb
    networks:
      - jitsi-net

networks:
  jitsi-net:
    driver: bridge
