version: '3.8'
services:
  jitsi-web:
    image: jitsi/web:stable-8960
    ports:
      - "8090:80"
    volumes:
      - ./.jitsi-meet-cfg/web:/config:Z
    environment:
      - DISABLE_HTTPS=1
      - ENABLE_HTTP_REDIRECT=0
      - ENABLE_AUTH=0
      - ENABLE_GUESTS=0
      - ENABLE_XMPP_WEBSOCKET=1
      - PUBLIC_URL=http://localhost:8090
      - XMPP_DOMAIN=meet.jitsi
      - XMPP_BOSH_URL_BASE=http://xmpp.meet.jitsi:5280
      - XMPP_WEBSOCKET=ws://localhost:8090/xmpp-websocket
    networks:
      meet.jitsi:
        aliases:
          - meet.jitsi

  prosody:
    image: jitsi/prosody:stable-8960
    ports:
      - "5280:5280"
      - "5222:5222"  # Add XMPP client port

    volumes:
      - ./.jitsi-meet-cfg/prosody/config:/config:Z
    environment:
      - ENABLE_XMPP_WEBSOCKET=1
      - XMPP_DOMAIN=meet.jitsi
      - DISABLE_HTTPS=1
      - ENABLE_AUTH=0
      - ENABLE_GUESTS=1  # Allow guest access
      - JICOFO_AUTH_USER=focus
      - JICOFO_AUTH_PASSWORD=some_secure_password
      - JVB_AUTH_USER=jvb
      - JVB_AUTH_PASSWORD=another_secure_password
    networks:
      meet.jitsi:
        aliases:
          - xmpp.meet.jitsi

  jicofo:
    image: jitsi/jicofo:stable-8960
    volumes:
        - ./.jitsi-meet-cfg/jicofo:/config:Z
    environment:
        - DISABLE_HTTPS=1
        - ENABLE_AUTH=0
        - XMPP_DOMAIN=meet.jitsi
        - XMPP_SERVER=xmpp.meet.jitsi
        - ENABLE_GUESTS=1  # Allow guest access
        - JICOFO_AUTH_USER=focus
        - JICOFO_AUTH_PASSWORD=some_secure_password
    depends_on:
      - prosody
    networks:
      meet.jitsi:

  jvb:
    image: jitsi/jvb:stable-8960
    ports:
      - "10000:10000/udp"
    volumes:
      - ./.jitsi-meet-cfg/jvb:/config:Z
    environment:
      - DISABLE_HTTPS=1
      - ENABLE_AUTH=0
      - XMPP_SERVER=xmpp.meet.jitsi
      - JVB_PORT=10000
      - PUBLIC_URL=http://localhost:8090
      - JVB_AUTH_USER=jvb
      - JVB_AUTH_PASSWORD=another_secure_password
      - JVB_COLIBRI_WS_DOMAIN=localhost:8090
      - JVB_COLIBRI_WS_SERVER=ws://localhost:8090/colibri-ws/
    depends_on:
      - prosody
    networks:
      meet.jitsi:

networks:
  meet.jitsi: